<?php if ( !defined('BASEPATH') ) { exit('No direct script access allowed'); }

class Layout {
  function index() {
    global $OUT;
    $CI = &get_instance();
    // get default output generated by CI
    $output = $CI->output->get_output();
    if ( isset($CI->layout) ) {
      if ( !preg_match('/(.+).php$/', $CI->layout) ) {
        $CI->layout .= '.php';
      }
      // this will be the requested layout
      $requested = VIEWPATH . '_layouts/' . $CI->layout;
      // this is the default layout, use as fallback
      $default = VIEWPATH . '_layouts/default.php';
      $layout = '';
      if ( file_exists($requested) ) {
        $layout = $CI->load->file($requested, TRUE);
      }
      else {
        $layout = $CI->load->file($default, TRUE);
      }
      $view = str_replace('{{content}}', $output, $layout);
    }
    else {
      $view = $output;
    }
    $OUT->_display($view);
  }
}